projectname    GumDiscord

srcdir         src
exampledir     examples

findlibraries  SELF GumSystem GumEssentials GumNetwork GumMaths
headerfiles    gum-discord Discord/
examples       TestBot

extraincludepaths_begin
    PROJECTROOT/external/
extraincludepaths_end

extralibraries_begin
   curl
   ssl
   crypto
extralibraries_end

customstr_begin
customstr_end
