projectname    GumSystem

srcdir         src
exampledir     examples

findlibraries  SELF GumMaths
headerfiles    gum-system System/
examples       FilesystemTests

extraincludepaths_begin
extraincludepaths_end

extralibraries_begin
extralibraries_end

customstr_begin
customstr_end
